### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'modeling/resnet50_ibn_a.pth.tar'

### ISSUE THREAD

**Issue by 2806099072** [Qidian213/Ranked_Person_ReID#2]
您好！打扰了!
resnet50_ibn_a.pth.tar  我在网上找不到这个文件，您能提供一下吗？

**Comment by Qidian213** [comment]
我已经在readme里增加了下载链接，可以再试一下。

**Comment by 2806099072** [comment]
（3）ResNet_IBN_a , faster implementation

You can download from here [link]


您好！您指的的是上面【link】这个超链接吗？我打不开这个链接！

**Comment by Qidian213** [comment]
那你需要翻墙了
