### ISSUE TITLE
resnet_ibn_a.py  error

### ISSUE THREAD

**Issue by zhanghongruiupup** [Qidian213/Ranked_Person_ReID#4]
i set resnet_ibn_a path with _C.MODEL.NAME = 'resnet50_ibn_a'  
but show     
param_dict = model_weight['state_dict']
KeyError: 'state_dict'

thank your works with hope reply.

**Comment by Qidian213** [comment]
你的pytorch版本？

**Comment by zhanghongruiupup** [comment]
> 你的pytorch版本？

1.2.0

**Comment by Qidian213** [comment]
问题解决了？ 我用1.3版本测试也没这个问题

**Comment by zhanghongruiupup** [comment]
> 问题

解决了，还是pytorch版本问题，我把config中的defaults.py中的(feat, target)[0]全部改成(feat, target).item()了，谢谢你的代码

**Comment by zhanghongruiupup** [comment]
> 问题解决了？ 我用1.3版本测试也没这个问题

感谢您的工作，我跑完了您的代码。除了使STN=yes之外，其他参数保持一致，market1501上结果=86%，我应该怎么做才能达到88%。

**Comment by zhanghongruiupup** [comment]
> 问题解决了？ 我用1.3版本测试也没这个问题

DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  SAMPLER: softmax_rank
DATASETS:
  NAMES: market1501
  ROOT_DIR: ./data
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  DEVICE: cuda
  DEVICE_ID: 0
  IF_LABELSMOOTH: on
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: ranked_loss
  NAME: resnet50_ibn_a
  PRETRAIN_CHOICE: self
  PRETRAIN_PATH: /home/fwq/zhanghongruils/任务/bag-of-trick/RLL/resnet50_ibn_a.pth .tar
  STN: yes
OUTPUT_DIR: work_space
SOLVER:
  ALPHA: 2.0
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 80
  GAMMA: 0.1
  IMS_PER_BATCH: 64
  LOG_PERIOD: 20
  MARGIN_RANK: 1.3
  MAX_EPOCHS: 120
  MOMENTUM: 0.9
  OPTIMIZER_NAME: Adam
  STEPS: (40, 70)
  TVAL: 1.0
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  WEIGHT: 0.4
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:

**Comment by Qidian213** [comment]
想要达到我公布的结果，不需要使用STN，可以试试把 ‘_C.SOLVER.WEIGHT = 0.4’ 改成 0.2。 别的不需要改动。 另外根据别人反馈与我自己跑的结果，同样的参数，使用不同的机器跑训练得到的结果有偏差，暂未找到原因。

```
# Margin of ranked list loss 
_C.SOLVER.MARGIN_RANK = 1.3  ### R = ALPHA - MARGIN_RANK
_C.SOLVER.ALPHA = 2.0
_C.SOLVER.TVAL = 1.0
_C.SOLVER.WEIGHT = 0.2       ### loss = softmax + w*ranked_loss
```

**Comment by zhanghongruiupup** [comment]
> 想要达到我公布的结果，不需要使用STN，可以试试把 ‘_C.SOLVER.WEIGHT = 0.4’ 改成 0.2。 别的不需要改动。 另外根据别人反馈与我自己跑的结果，同样的参数，使用不同的机器跑训练得到的结果有偏差，暂未找到原因。
> 
> ```
> # Margin of ranked list loss 
> _C.SOLVER.MARGIN_RANK = 1.3  ### R = ALPHA - MARGIN_RANK
> _C.SOLVER.ALPHA = 2.0
> _C.SOLVER.TVAL = 1.0
> _C.SOLVER.WEIGHT = 0.2       ### loss = softmax + w*ranked_loss
> ```

好人一生平安
