### ISSUE TITLE
你好，请问一下为什么会有两种结果？最后一个是怎么得到的呢？

### ISSUE THREAD

**Issue by gyc521zsc** [Qidian213/Ranked_Person_ReID#5]
![image](https://user-images.githubusercontent.com/50411057/69323549-e75a7100-0c81-11ea-9987-c8c86fa7ef68.png)

**Comment by Qidian213** [comment]
reranking

**Comment by gyc521zsc** [comment]
你好，请问一下reranking代码在哪？

**Comment by Qidian213** [comment]
re_ranking.py
