### ISSUE TITLE
准确率问题

### ISSUE THREAD

**Issue by TheBigCock** [Qidian213/Ranked_Person_ReID#7]
您好，请问为啥用crank_loss训练的结果反而比rank_loss的结果差呢？您也一样的嘛？并且我的准确率始终只有map83%。r1=93%左右在market1501数据集上。

**Comment by Qidian213** [comment]
我上传的这个crank_loss不是完善的代码及参数，加上我自己测试也是只能得到和ranked loss类似的结果，所以才没有给出实验结果。
